# Generated by Django 5.0.7 on 2024-08-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/products'),
        ),
    ]
