# Generated by Django 5.0.7 on 2024-08-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
