# Generated by Django 5.0.7 on 2024-08-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0010_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
