# Generated by Django 5.0.7 on 2024-08-06 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0013_remove_orderitem_order_remove_orderitem_product_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='tatol_items',
        ),
    ]
